# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Stephanie M.G. Wilson"
description: >- # this means to ignore newlines until "baseurl:"
  Dr. Stephanie Wilson is a nutrition scientist interested in chronic disease prevention by investigating the impact of plant-based dietary strategies and the role of the gut microbiome.
repository: SWi1/smgwilson
github_username: SWi1
minimal_mistakes_skin: sunrise
url: "https://swi1.github.io/"
baseurl: "/smgwilson"   # set to your repository name

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:title/
timezone: America/Los_Angeles

include:
  - _pages

# Disable blog features
show_posts: false      # should hide recent posts in some layouts
collections:
  posts:
    output: false      # prevents Jekyll from generating posts
paginate: 0            # disables pagination


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Stephanie M.G. Wilson"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Nutrition Scientist, Science Communicator, Changemaker"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SWi1"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stephanie-mg-wilson"
    - label: "ORCID"
      icon: "fas fa-fw fa-id-badge" # official ORCID green
      url: "https://orcid.org/0000-0002-4200-1752"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-id-badge" # official ORCID green
      url: "https://scholar.google.com/citations?user=L1uAXl8AAAAJ&hl=en"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
